require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
-- require "user.illuminate"
require "user.indentline"
require "user.alpha"
require "user.lsp"
require "user.ufo"
require "user.harpoon"
-- require "user.dap"
require "user.diffview"
vim.cmd("source ~/.config/nvim_lua/plugin/some_vim_funcs.vim")
