require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.treesitter"
require "user.comment"
-- require "user.gitstuff"
require "user.lualine"
require "user.alpha"
require "user.lsp"
-- require "user.harpoon"
require "user.usercmds"
-- require "user.diffview"
require "user.sessions"
-- require "user.quickfix"
-- require "user.bufferline"
require "user.register"
-- require "user.nvim-tree"
-- require "user.fzf-lua"
-- require "user.toggleterm"
-- require "user.indentline"
-- require "user.sidebar"
-- require "user.pounce"
-- require "user.dap"
-- require "user.project"
-- require "user.illuminate"
-- require "user.telescope"
-- require "user.autopairs"
-- require "user.ufo"
vim.cmd("source ~/.config/nvim/plugin/some_vim_funcs.vim")
vim.cmd("silent! source ~/my_nvim/*.vim")
